- name: Elk Stack Install
  hosts: elk_mas_data_nodes 
  roles:
    - role: elastic.elasticsearch
  vars:
    es_enable_xpack: true
    es_xpack_trial: true
    es_heap_size: "1g"
    es_config:
      node.name: ${HOSTNAME}
      cluster.name: "elk-cluster-test"
      discovery.seed_hosts: "127.0.0.1:9300"
      http.host: 0.0.0.0
      http.port: 9200
      node.data: true
      node.master: true
      transport.host: 0.0.0.0
      transport.port: 9300
      bootstrap.memory_lock: false
      xpack.security.authc.realms.file.file1.order: 0
      xpack.security.authc.realms.native.native1.order: 1
    es_ssl_upload: true
    es_enable_auto_ssl_configuration: true
    es_api_basic_auth_username: "elastic" # This is the default user created by the installation of elasticsearch
    es_api_basic_auth_password: "password" # This is the default password created by the installation of elasticsearch
    es_enable_http_ssl: true
    es_enable_transport_ssl: true
    es_ssl_verification_mode: certificate
    es_ssl_keystore: "~/esproject/certs/elastic-certificates.p12"
    es_ssl_truststore: "~/esproject/certs/elastic-certificates.p12"
    es_validate_certs: no
